from turtle import *
hideturtle()
speed(11)
width(10)
def draw_circle(linecolor,size):
	color(linecolor)
	circle(size)
begin_fill()
draw_circle('red', 500)
end_fill()
begin_fill()
draw_circle('brown', 400)
end_fill()
begin_fill()
draw_circle('yellow', 300)
end_fill()
begin_fill()
draw_circle('blue',200)
end_fill()
begin_fill()
draw_circle('pink', 100)
end_fill()

setheading(180)
goto(0,-10)
def draw_circle(linecolor,size):
	color(linecolor)
	circle(size)
begin_fill()
draw_circle('red', 500)
end_fill()
begin_fill()
draw_circle('brown', 400)
end_fill()
begin_fill()
draw_circle('yellow', 300)
end_fill()
begin_fill()
draw_circle('blue',200)
end_fill()
begin_fill()
draw_circle('pink', 100)
end_fill()
done()
